/*
* Purpose: Support code-generation activities with templates
*/
const { readFileSync } = require('fs')

const TemplateToken = {
  BANNER: '<% banner %>',
  IMPORTS: '<% imports %>',
  EXPORTS: '<% exports %>',
  TAG: '<% tag %>',
  COMPONENT_CLASS_NAME: '<% component-class-name %>',
  PROP_TYPES: '<% prop-types %>',
  PROPS: '<% props %>',
  DEFAULT_PROPS: '<% default-props %>',
  PROPERTIES: '<% properties %>',
  ATTRIBUTES: '<% attributes %>',
  EVENTS: '<% events %>',
  CLASS_JSDOC: '<% jsdoc.class %>',
  TAG_DESCRIPTOR_JSON: '<% descriptor-json %>',
  COMPOUND_COMPONENTS: '<% compound-components %>'
}

const GENERATED_CODE_BANNER = `/*
* DO NOT EDIT THIS FILE. IT IS GENERATED
*/`
const templatesFolder = `${__dirname}`
const getTemplate = (template, language) =>
  readFileSync(`${templatesFolder}/${language}/${template}.tmpl`, { encoding: 'utf8' })
    .replace(TemplateToken.BANNER, GENERATED_CODE_BANNER)

module.exports = {
  getTemplate,
  TemplateToken,
  GENERATED_CODE_BANNER
}
