/*
* DO NOT EDIT THIS FILE. IT IS GENERATED
*/
declare module '@vonage/vivid-react-wrapper';
declare module '@vonage/vivid-react';
declare namespace JSX {
    interface IntrinsicElements {
        "vvd3-accordion": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{

        }>;
        "vvd3-accordion-item": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "heading": string | undefined;
            "no-indicator": boolean;
            "meta": string | undefined;
            "size": AccordionItemSize | undefined;
        }>;
        "vvd3-action-group": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "shape": ActionGroupShape | undefined;
            "appearance": ActionGroupAppearance | undefined;
            "tight": boolean;
            "role": string | null;
            "aria-label": string | null;
        }>;
        "vvd3-alert": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "dismiss-button-aria-label": string | null;
            "removable": boolean;
            "placement": AlertPlacement | undefined;
            "headline": string | undefined;
            "text": string | undefined;
            "icon": string | undefined;
            "timeoutms": number;
            "connotation": AlertConnotation | undefined;
            "strategy": AlertStrategy | undefined;
            "open": boolean;
        }>;
        "vvd3-appearance-ui": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "appearance": AppearanceUIAppearance | undefined;
            "hovered": boolean;
            "active": boolean;
            "selected": boolean;
            "disabled": boolean;
            "readonly": boolean;
            "text": string | undefined;
        }>;
        "vvd3-audio-player": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "play-button-aria-label": string | null;
            "pause-button-aria-label": string | null;
            "slider-aria-label": string | null;
            "connotation": AudioPlayerConnotation | undefined;
            "src": string | undefined;
            "disabled": boolean;
            "notime": boolean;
        }>;
        "vvd3-avatar": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "connotation": AvatarConnotation | undefined;
            "shape": AvatarShape | undefined;
            "appearance": AvatarAppearance | undefined;
            "size": AvatarSize | undefined;
            "icon": string | undefined;
            "initials": string | undefined;
        }>;
        "vvd3-badge": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "connotation": BadgeConnotation | undefined;
            "shape": BadgeShape | undefined;
            "appearance": BadgeAppearance | undefined;
            "text": string | undefined;
        }>;
        "vvd3-banner": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "dismiss-aria-label": string | null;
            "role": string | null;
            "action-href": string | undefined;
            "action-text": string | undefined;
            "removable": boolean;
            "aria-live": any;
            "text": string | undefined;
            "connotation": BannerConnotation | undefined;
        }>;
        "vvd3-breadcrumb": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{

        }>;
        "vvd3-breadcrumb-item": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "text": string | undefined;
        }>;
        "vvd3-button": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "title": string;
            "connotation": ButtonConnotation | undefined;
            "shape": ButtonShape | undefined;
            "appearance": ButtonAppearance | undefined;
            "size": ButtonSize | undefined;
            "stacked": boolean;
            "pending": boolean;
            "label": string | undefined;
        }>;
        "vvd3-calendar": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "datetime": Date | string | undefined;
            "start-day": 'sunday' | 'monday' | undefined;
            "locales": string | string[] | undefined | undefined;
            "hour12": boolean;
        }>;
        "vvd3-calendar-event": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "heading": string | undefined;
            "description": string | undefined;
            "connotation": CalendarEventConnotation | undefined;
            "appearance": CalendarEventAppearance | undefined;
            "overlap-count": number | undefined;
            "start": number | undefined;
            "duration": number | undefined;
        }>;
        "vvd3-card": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "appearance": CardAppearance | undefined;
            "headline": string | undefined;
            "subtitle": string | undefined;
            "text": string | undefined;
            "icon": string | undefined;
            "elevation": 0 | 2 | 4 | 8 | 12 | 16 | 24 | undefined;
        }>;
        "vvd3-checkbox": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "aria-label": string | null;
            "tabindex": string | null;
            "connotation": CheckboxConnotation | undefined;
        }>;
        "vvd3-combobox": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "placement": PopupPlacement | undefined;
        }>;
        "vvd3-data-grid-cell": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "aria-selected": string | null;
            "aria-sort": string | null;
        }>;
        "vvd3-data-grid-row": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "aria-selected": string | null;
        }>;
        "vvd3-data-grid": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "selection-mode": DataGridSelectionMode | undefined;
        }>;
        "vvd3-date-picker": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "min": string;
            "value": string;
            "current-value": string;
            "readonly": boolean;
        }>;
        "vvd3-date-range-picker": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "start": string;
            "end": string;
            "current-start": string;
            "current-end": string;
            "min": string;
            "value": string;
            "current-value": string;
            "readonly": boolean;
        }>;
        "vvd3-dialog": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "open": boolean;
            "icon": string | undefined;
            "icon-placement": IconPlacement | undefined;
            "subtitle": string | undefined;
            "headline": string | undefined;
            "full-width-body": boolean;
            "aria-label": string | null;
            "dismiss-button-aria-label": string | null;
            "no-light-dismiss": boolean;
        }>;
        "vvd3-divider": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{

        }>;
        "vvd3-elevation": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "dp": 0 | 2 | 4 | 8 | 12 | 16 | 24 | undefined;
            "no-shadow": boolean | undefined;
        }>;
        "vvd3-empty-state": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "headline": string | undefined;
            "icon": string | undefined;
        }>;
        "vvd3-fab": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "connotation": FabConnotation | undefined;
            "size": FABSize | undefined;
            "label": string | undefined;
        }>;
        "vvd3-form-associated-file-picker": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{

        }>;
        "vvd3-file-picker": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "max-files": number | undefined;
            "max-file-size": number;
            "accept": string | undefined;
            "size": FilePickerSize | undefined;
        }>;
        "vvd3-focus": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{

        }>;
        "vvd3-header": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "elevation-shadow": boolean;
            "alternate": boolean;
        }>;
        "vvd3-icon": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "connotation": IconConnotation | undefined;
            "size": -6 | -5 | -4 | -3 | -2 | -1 | 0 | 1 | 2 | 3 | 4 | 5 | undefined;
            "name": string | undefined;
        }>;
        "vvd3-layout": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "gutters": Gutters | undefined;
            "column-basis": ColumnBasis | undefined;
            "column-spacing": ColumnSpacing | undefined;
            "row-spacing": RowSpacing | undefined;
            "auto-sizing": AUTO_SIZING | undefined;
        }>;
        "vvd3-listbox": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "appearance": LisboxAppearance | undefined;
            "orientation": 'horizontal' | 'vertical' | undefined;
            "shape": ListboxShape | undefined;
        }>;
        "vvd3-menu": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "aria-label": string | null;
            "placement": Placement | undefined;
            "auto-dismiss": boolean;
            "open": boolean;
        }>;
        "vvd3-menu-item": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "text": string | undefined;
            "text-secondary": string | undefined;
            "check-trailing": boolean;
            "check-appearance": CheckAppearance | undefined;
        }>;
        "vvd3-nav": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{

        }>;
        "vvd3-nav-disclosure": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "label": string | undefined;
            "open": boolean;
            "aria-current": string | null;
        }>;
        "vvd3-nav-item": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "text": string | undefined;
        }>;
        "vvd3-note": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "headline": string | undefined;
            "connotation": NoteConnotation | undefined;
        }>;
        "vvd3-number-field": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "increment-button-aria-label": string | null;
            "decrement-button-aria-label": string | null;
            "appearance": NumberFieldAppearance | undefined;
            "shape": NumberFieldShape | undefined;
            "autoComplete": string | undefined;
        }>;
        "vvd3-listbox-option": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "text": string | undefined;
            "label": string | undefined;
        }>;
        "vvd3-pagination": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "size": PaginationSize | undefined;
            "shape": PaginationShape | undefined;
            "nav-icons": boolean;
            "total": number;
            "selected-index": number | undefined;
        }>;
        "vvd3-popup": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "open": boolean;
            "dismissible": boolean;
            "arrow": boolean;
            "alternate": boolean;
            "placement": Placement | undefined;
            "strategy": Strategy | undefined;
        }>;
        "vvd3-progress": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "aria-label": string | null;
            "shape": ProgressShape | undefined;
            "connotation": ProgressConnotation | undefined;
            "reverse": boolean;
        }>;
        "vvd3-progress-ring": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "aria-label": string | null;
            "connotation": ProgressRingConnotation | undefined;
            "size": -6 | -5 | -4 | -3 | -2 | -1 | 0 | 1 | 2 | 3 | 4 | 5 | undefined;
        }>;
        "vvd3-radio": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "aria-label": string | null;
            "label": string | undefined;
            "connotation": RadioConnotation | undefined;
        }>;
        "vvd3-radio-group": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "label": string | undefined;
        }>;
        "vvd3-select": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "appearance": SelectAppearance | undefined;
            "shape": SelectShape | undefined;
            "fixed-dropdown": boolean;
            "placeholder": string | undefined;
        }>;
        "vvd3-selectable-box": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "aria-label": string | null;
            "checked": boolean;
            "clickable": boolean;
            "clickable-box": boolean;
            "connotation": SelectableBoxConnotation | undefined;
            "control-type": SelectableBoxControlType | undefined;
            "tight": boolean;
        }>;
        "vvd3-side-drawer": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "alternate": boolean;
            "modal": boolean;
            "open": boolean;
            "trailing": boolean;
        }>;
        "vvd3-slider": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "aria-label": string | null;
            "aria-valuetext": string | null;
            "markers": boolean;
            "connotation": SliderConnotation | undefined;
        }>;
        "vvd3-split-button": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "connotation": SplitButtonConnotation | undefined;
            "shape": SplitButtonShape | undefined;
            "appearance": SplitButtonAppearance | undefined;
            "size": SplitButtonSize | undefined;
            "label": string | undefined;
            "icon": string | undefined;
            "split-indicator": string;
            "disabled": boolean;
            "aria-label": string | null;
            "aria-expanded": string | null;
            "indicator-aria-label": string | null;
        }>;
        "vvd3-switch": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "label": string | undefined;
            "connotation": SwitchConnotation | undefined;
        }>;
        "vvd3-tab": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "connotation": TabConnotation | undefined;
            "shape": TabShape | undefined;
            "label": string | undefined;
            "tabIndex": any;
            "aria-selected": string | null;
        }>;
        "vvd3-tab-panel": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{

        }>;
        "vvd3-tabs": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "connotation": TabsConnotation | undefined;
            "gutters": Gutters | undefined;
            "scrollable-panel": boolean;
        }>;
        "vvd3-tag": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "connotation": TagConnotation | undefined;
            "shape": TagShape | undefined;
            "appearance": TagAppearance | undefined;
            "label": string | undefined;
            "removable": boolean;
            "disabled": boolean;
            "selectable": boolean;
            "selected": boolean;
        }>;
        "vvd3-tag-group": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "aria-label": string | null;
        }>;
        "vvd3-text-anchor": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "text": string | undefined;
        }>;
        "vvd3-text-area": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "wrap": TextAreaWrap | undefined;
        }>;
        "vvd3-text-field": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "appearance": TextFieldAppearance | undefined;
            "shape": TextFieldShape | undefined;
            "autoComplete": string | undefined;
        }>;
        "vvd3-form-associated-time-picker": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{

        }>;
        "vvd3-time-picker": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "readonly": boolean;
            "minutes-step": number | null;
            "seconds-step": number | null;
            "clock": '12h' | '24h' | undefined;
            "min": string;
            "max": string;
        }>;
        "vvd3-toggletip": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "headline": string | undefined;
            "alternate": boolean;
            "placement": Placement | undefined;
            "open": boolean;
        }>;
        "vvd3-tooltip": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "text": string | undefined;
            "placement": Placement | undefined;
            "open": boolean;
        }>;
        "vvd3-tree-item": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "text": string | undefined;
        }>;
        "vvd3-tree-view": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{

        }>;
        "vvd3-date-picker-base": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & Partial<{
            "min": string;
            "max": string;
            "value": string;
            "current-value": string;
            "readonly": boolean;
        }>;
    }
}