name: publish to npmjs.com

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 18
      - name: Set Release Version
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn
          yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.CI_AT }}

      - name: Publish to >> npmjs.com
        run: |
          cd dist
          echo registry=https://registry.npmjs.org/ > .npmrc
          echo //registry.npmjs.org/:_authToken=${TOKEN} >> .npmrc
          yarn publish --new-version ${RELEASE_VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOKEN: ${{ secrets.NPM_TOKEN }} # token has been issued on January 4, 2023. It's valid for 1 year
          RELEASE_VERSION: ${{ steps.get_version.outputs.version-without-v }}
