name: publish to npmjs.com

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 18
      - name: Fetch package version
        run: node -p -e '`RELEASE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn
          yarn build

      - name: Publish to >> npmjs.com0
        run: |
          rm .npmrc || true
          echo registry=https://registry.npmjs.org/ > .npmrc
          echo //registry.npmjs.org/:_authToken=${TOKEN} >> .npmrc
          cd dist
          yarn publish --new-version ${RELEASE_VERSION}
        env:
          TOKEN: ${{ secrets.NPM_TOKEN }} # token has been issued on January 4, 2023. It's valid for 1 year