name: Release Vivid React

on:
  push:
    tags:
      - v*

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
      ARTIFACTORY_SECRET: ${{ secrets.ARTIFACTORY_SECRET }}
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_NPM_TOKEN: ${{ secrets.ARTIFACTORY_NPM_TOKEN }}

    steps:
      - name: Install GitHub SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_GITHUB }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Release Version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build
        run: yarn build

      - name: Publish to Github
        run: |
          cd dist
          echo registry=https://npm.pkg.github.com/ > .npmrc
          echo //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} >> .npmrc
          yarn publish --new-version ${RELEASE_VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.get_version.outputs.version-without-v }}
