name: Release Vivid React

on:
  push:
    tags:
      - v*

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup NodeJS
        uses: actions/setup-node@main
        with:
          node-version: 18

      - name: Fetch package version
        run: node -p -e '`RELEASE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Install dependencies & build
        run: |
          npm install -g yarn
          yarn
          yarn build

      - name: Publish to Github
        run: |
          cd dist
          echo registry=https://npm.pkg.github.com/ > .npmrc
          echo //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} >> .npmrc
          yarn publish --new-version ${RELEASE_VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Npmjs.com
        run: |
          cd dist
          rm .npmrc || true
          echo registry=https://registry.npmjs.org/ > .npmrc
          echo //registry.npmjs.org/:_authToken=${TOKEN} >> .npmrc
          yarn publish --new-version ${RELEASE_VERSION}
        env:
          TOKEN: ${{ secrets.NPM_TOKEN }} # token has been issued on January 4, 2023. It's valid for 1 year
