name: Release Vivid React

on:
  push:
    tags:
      - v*

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
      ARTIFACTORY_SECRET: ${{ secrets.ARTIFACTORY_SECRET }}
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_NPM_TOKEN: ${{ secrets.ARTIFACTORY_NPM_TOKEN }}

    steps:
      - name: Install GitHub SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_GITHUB }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Checkout
        uses: actions/checkout@main

      - name: Setup NodeJS
        uses: actions/setup-node@main
        with:
          node-version: 18

      - name: Fetch package version
        run: node -p -e '`RELEASE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Install dependencies & build
        run: |
          npm install -g yarn
          yarn
          yarn build
          cd dist

      - name: Publish to Github
        run: |
          echo registry=https://npm.pkg.github.com/ > .npmrc
          echo //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} >> .npmrc
          yarn publish --new-version ${RELEASE_VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to >> npmjs.com
        run: |
          rm .npmrc || true
          echo registry=https://registry.npmjs.org/ > .npmrc
          echo //registry.npmjs.org/:_authToken=${TOKEN} >> .npmrc
          yarn publish --new-version ${RELEASE_VERSION}
        env:
          TOKEN: ${{ secrets.NPM_TOKEN }} # token has been issued on January 4, 2023. It's valid for 1 year
